wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.15
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.30.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702366777.977081
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 3
      - 13
      - 23
      4: 3.8.15
      5: 0.15.2
      6: 4.30.1
      8:
      - 5
